#!/usr/bin/env bash
# Renders the Homebrew tap files for a release:
#   Formula/firehose.rb      CLI + daemon, with a `brew services` definition
#   Casks/agent-firehose.rb  Tauri desktop app (macOS)
# usage: render-tap.sh <version> <checksums.txt> <dmg-dir> <out-dir>
#   <dmg-dir> holds agent-firehose_<version>_{aarch64,x86_64}.dmg
set -euo pipefail

VERSION="${1:?version}"
CHECKSUMS="${2:?checksums.txt}"
DMGS="${3:?dmg dir}"
OUT="${4:?out dir}"
REPO="https://github.com/treetopdevs/llm-firehose"
HOMEPAGE="$REPO"
DESC="Live, local-first timeline of what AI coding agents are doing on your machine"

archive_sha() {
  local sha
  sha="$(awk -v f="firehose_${VERSION}_$1.tar.gz" '$2 == f { print $1 }' "$CHECKSUMS")"
  [ -n "$sha" ] || { echo "error: no checksum for firehose_${VERSION}_$1.tar.gz" >&2; exit 1; }
  echo "$sha"
}
dmg_sha() {
  shasum -a 256 "$DMGS/agent-firehose_${VERSION}_$1.dmg" | awk '{ print $1 }'
}

mkdir -p "$OUT/Formula" "$OUT/Casks"

cat > "$OUT/Formula/firehose.rb" <<RB
# Generated by scripts/render-tap.sh. DO NOT EDIT.
class Firehose < Formula
  desc "$DESC"
  homepage "$HOMEPAGE"
  license "MIT"

  on_macos do
    on_arm do
      url "$REPO/releases/download/v$VERSION/firehose_${VERSION}_darwin_arm64.tar.gz"
      sha256 "$(archive_sha darwin_arm64)"
    end
    on_intel do
      url "$REPO/releases/download/v$VERSION/firehose_${VERSION}_darwin_amd64.tar.gz"
      sha256 "$(archive_sha darwin_amd64)"
    end
  end
  on_linux do
    on_arm do
      url "$REPO/releases/download/v$VERSION/firehose_${VERSION}_linux_arm64.tar.gz"
      sha256 "$(archive_sha linux_arm64)"
    end
    on_intel do
      url "$REPO/releases/download/v$VERSION/firehose_${VERSION}_linux_amd64.tar.gz"
      sha256 "$(archive_sha linux_amd64)"
    end
  end

  def install
    bin.install "firehose"
    bin.install "firehosed"
  end

  service do
    run [opt_bin/"firehosed"]
    keep_alive true
    log_path var/"log/firehosed.log"
    error_log_path var/"log/firehosed.log"
  end

  def caveats
    <<~EOS
      Run the capture daemon in the background (and at login):
        brew services start firehose
      Then wire up the agents you use, e.g.:
        firehose install claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/firehose version")
    assert_match version.to_s, shell_output("#{bin}/firehosed --version")
  end
end
RB

cat > "$OUT/Casks/agent-firehose.rb" <<RB
# Generated by scripts/render-tap.sh. DO NOT EDIT.
cask "agent-firehose" do
  version "$VERSION"

  on_arm do
    sha256 "$(dmg_sha aarch64)"

    url "$REPO/releases/download/v#{version}/agent-firehose_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "$(dmg_sha x86_64)"

    url "$REPO/releases/download/v#{version}/agent-firehose_#{version}_x86_64.dmg"
  end

  name "Agent Firehose"
  desc "$DESC"
  homepage "$HOMEPAGE"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on :macos

  app "Agent Firehose.app"

  # The app is not signed/notarized yet; strip quarantine so Gatekeeper
  # doesn't block the first launch.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Agent Firehose.app"]
  end

  # Deliberately no zap for ~/.agentfirehose: it holds the user's event spool.
end
RB
echo "rendered into $OUT"
